"""add user_id and summary to trip_sessions

Revision ID: b80769434ee7
Revises: fbe8c1e2cd41
Create Date: 2026-09-17 22:47:37.257751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80769434ee7'
down_revision: Union[str, Sequence[str], None] = 'fbe8c1e2cd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: nullable column add pannu
    op.add_column('trip_sessions', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('trip_sessions', sa.Column('summary', sa.String(), nullable=True))
    
    # Step 2: existing rows ku default value kudu (session_id ah user_id ah use pannalam)
    op.execute("UPDATE trip_sessions SET user_id = session_id WHERE user_id IS NULL")
    
    # Step 3: ipo NOT NULL ah maathu
    op.alter_column('trip_sessions', 'user_id', nullable=False)
    
    op.create_index(op.f('ix_trip_sessions_user_id'), 'trip_sessions', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_sessions_user_id'), table_name='trip_sessions')
    op.drop_column('trip_sessions', 'summary')
    op.drop_column('trip_sessions', 'user_id')
    # ### end Alembic commands ###
